added build workflow

diff --git a/.github/workflows/build-pvpuller.yml b/.github/workflows/build-pvpuller.yml
--- a/.github/workflows/build-pvpuller.yml
+++ b/.github/workflows/build-pvpuller.yml
@@ -9,9 +9,9 @@ on:
       environment:
         description: Choose the environment to build
         type: environment
-      code_branch:
-        description: Branch to build validation
-        required: false
+#      code_branch:
+#        description: Branch to build validation
+#        required: false
       trivy_test_scan_pvpuller:
         description: "Run Trivy Test Scan"
         required: true
@@ -27,7 +27,7 @@ jobs:
     env:
       ECR_REPO_PVPULLER: "crdc-hub-pvpuller"
       REGION: "us-east-1"
-      CODE_BRANCH: "${{ github.event.inputs.code_branch }}"
+#      CODE_BRANCH: "${{ github.event.inputs.code_branch }}"
       AWS_ROLE_TO_ASSUME: ${{ secrets.AWS_ROLE_TO_ASSUME }}
       AWS_ACCOUNT_ID: ${{ secrets.AWS_ACCOUNT_ID }}
     steps:
@@ -35,21 +35,23 @@ jobs:
       - name: Checkout Code Repository
         uses: actions/checkout@v4
         with:
-          ref: ${{ env.CODE_BRANCH }}
+#          ref: ${{ env.CODE_BRANCH }}
+          ref: ${{ github.ref_name }}
           submodules: true
 
-      #- name: Extract branch name
-      #  id: extract_branch
-      #  run: |
-      #    BRANCH_NAME=${GITHUB_HEAD_REF:-${GITHUB_REF#refs/heads/}}
-      #    echo "branch=$BRANCH_NAME" >> "$GITHUB_ENV"
-      #    echo "Current branch is: $BRANCH_NAME"
+      - name: Extract branch name
+        id: extract_branch
+        run: |
+          BRANCH_NAME=${GITHUB_HEAD_REF:-${GITHUB_REF#refs/heads/}}
+          echo "branch=$BRANCH_NAME" >> "$GITHUB_ENV"
+          echo "Current branch is: $BRANCH_NAME"
       
       - name: Build Pv Puller Docker Image
         id: build-image
         env:
           REGISTRY_URL: ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com
-          PV_PULLER_IMAGE_NAME: ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com/${{ env.ECR_REPO_PVPULLER }}:${{ env.CODE_BRANCH }}.${{ github.run_number }}
+          #PV_PULLER_IMAGE_NAME: ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com/${{ env.ECR_REPO_PVPULLER }}:${{ env.CODE_BRANCH }}.${{ github.run_number }}
+          PV_PULLER_IMAGE_NAME: ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com/${{ env.ECR_REPO_PVPULLER }}:${{ env.branch }}.${{ github.run_number }}
         run: |
           echo "Building: $PV_PULLER_IMAGE_NAME"
           docker build --no-cache -t $PV_PULLER_IMAGE_NAME -f pv_puller.dockerfile .
@@ -59,7 +61,8 @@ jobs:
         if: github.event.inputs.trivy_test_scan_file_validation == 'true'
         env:
           REGISTRY_URL: ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com
-          PV_PULLER_IMAGE_NAME: ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com/${{ env.ECR_REPO_PVPULLER }}:${{ env.CODE_BRANCH }}.${{ github.run_number }}
+          #PV_PULLER_IMAGE_NAME: ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com/${{ env.ECR_REPO_PVPULLER }}:${{ env.CODE_BRANCH }}.${{ github.run_number }}
+          PV_PULLER_IMAGE_NAME: ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com/${{ env.ECR_REPO_PVPULLER }}:${{ env.branch }}.${{ github.run_number }}
         uses: aquasecurity/trivy-action@master
         with:
           image-ref: '${{ env.PV_PULLER_IMAGE_NAME }}'
@@ -83,46 +86,47 @@ jobs:
         if: success()
         env:
           REGISTRY_URL: ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ env.REGION }}.amazonaws.com
-          PV_PULLER_IMAGE_NAME: ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com/${{ env.ECR_REPO_PVPULLER }}:${{ env.CODE_BRANCH }}.${{ github.run_number }}
+          #PV_PULLER_IMAGE_NAME: ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com/${{ env.ECR_REPO_PVPULLER }}:${{ env.CODE_BRANCH }}.${{ github.run_number }}
+          PV_PULLER_IMAGE_NAME: ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com/${{ env.ECR_REPO_PVPULLER }}:${{ env.branch }}.${{ github.run_number }}
         run: |
           echo "Pushing: $PV_PULLER_IMAGE_NAME"
           docker push $PV_PULLER_IMAGE_NAME
 
-      - name: scan docker image with AWS inspector
-        id: scan-inspector
-        env:
-          REGISTRY_URL: ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ env.REGION }}.amazonaws.com
-          PV_PULLER_IMAGE_NAME: ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com/${{ env.ECR_REPO_PVPULLER }}:${{ env.CODE_BRANCH }}.${{ github.run_number }}
-        run: |
-          echo "AWS Inspector scan for image: $PV_PULLER_IMAGE_NAME"
-          SCAN_ID=$(aws inspector2 start-scan --resource-group-arn arn:aws:inspector2:${{ secrets.AWS_REGION }}:${{ secrets.AWS_ACCOUNT_ID }}:resourcegroup/default \
-                     -image-arn arn:aws:ecr:${{ secrets.AWS_REGION }}:${{ secrets.AWS_ACCOUNT_ID }}:repository/$ECR_REPO)
-          echo "Scan started: $SCAN_ID"
+#1st try      - name: scan docker image with AWS inspector
+#        id: scan-inspector
+#        env:
+#          REGISTRY_URL: ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ env.REGION }}.amazonaws.com
+#          PV_PULLER_IMAGE_NAME: ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com/${{ env.ECR_REPO_PVPULLER }}:${{ env.CODE_BRANCH }}.${{ github.run_number }}
+#        run: |
+#          echo "AWS Inspector scan for image: $PV_PULLER_IMAGE_NAME"
+#          SCAN_ID=$(aws inspector2 start-scan --resource-group-arn arn:aws:inspector2:${{ secrets.AWS_REGION }}:${{ secrets.AWS_ACCOUNT_ID }}:resourcegroup/default \
+#                     -image-arn arn:aws:ecr:${{ secrets.AWS_REGION }}:${{ secrets.AWS_ACCOUNT_ID }}:repository/$ECR_REPO)
+#          echo "Scan started: $SCAN_ID"
 
-      - name: wait for scan results
-        run: |
-          echo "Waiting for scan results..."
-          sleep 60
+#      - name: wait for scan results
+#        run: |
+#          echo "Waiting for scan results..."
+#          sleep 60
 
-      - name: get scan findings
-        env:
-          AWS_ACCOUNT_ID: ${{ secrets.AWS_ACCOUNT_ID }}
-        run: |
-          aws inspector2 list-findings --filter '{
-            "awsAccountId": { "equals": ["'$AWS_ACCOUNT_ID'"] },
-            "severity": { "equals": ["HIGH", "CRITICAL"] }
-          }' > findings.json
-          cat findings.json
+#      - name: get scan findings
+#        env:
+#          AWS_ACCOUNT_ID: ${{ secrets.AWS_ACCOUNT_ID }}
+#        run: |
+#          aws inspector2 list-findings --filter '{
+#            "awsAccountId": { "equals": ["'$AWS_ACCOUNT_ID'"] },
+#            "severity": { "equals": ["HIGH", "CRITICAL"] }
+#          }' > findings.json
+#          cat findings.json
 
-      - name: Fail if vulnerabilities are found
-        if: github.event.inputs.trivy_test_scan_file_validation == 'true'
-        run: |
-          CRITICAL_COUNT=$(jq '.findings | map(select(.severity == "CRITICAL")) | length' findings.json)
-          HIGH_COUNT=$(jq '.findings | map(select(.severity == "HIGH")) | length' findings.json)
+#      - name: Fail if vulnerabilities are found
+#        if: github.event.inputs.trivy_test_scan_file_validation == 'true'
+#        run: |
+#          CRITICAL_COUNT=$(jq '.findings | map(select(.severity == "CRITICAL")) | length' findings.json)
+#          HIGH_COUNT=$(jq '.findings | map(select(.severity == "HIGH")) | length' findings.json)
 
-          if [[ $CRITICAL_COUNT -gt 0 || $HIGH_COUNT -gt 0 ]]; then
-            echo "Securities vuls found"
-            exit 1
-          else
-            echo "Pass"
-          fi
+#          if [[ $CRITICAL_COUNT -gt 0 || $HIGH_COUNT -gt 0 ]]; then
+#            echo "Securities vuls found"
+#            exit 1
+#          else
+#            echo "Pass"
+#          fi
